CC = g++
bin = lipid_name_parser
opt = -O3 -std=c++11 -Wall
inc = /usr/include
lib_dir = /usr/lib
libs = cppGoslin

main: lipid_name_parser.cpp
	${CC} ${opt} -I ${inc} -o ${bin} lipid_name_parser.cpp -L ${lib_dir} -l ${libs}