name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build LipidSpace and LipidSpaceRest
    runs-on: ubuntu-22.04
    env:
      BUILD_DATE: ${{ github.run_id }}.${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
        submodules: recursive
    - name: Set Git user
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"

    - name: Install dependencies
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt update 
        sudo apt install -y --no-install-recommends \
        build-essential \
        libfontconfig1 \
        qt6-base-dev \
        qt6-base-dev-tools \
        libqt6svg6-dev \
        libqt6charts6-dev \
        libopenblas-base \
        libopenblas-dev \
        libomp-dev \
        mesa-common-dev \
        libglu1-mesa-dev \
        libc6 \
        libstdc++6

    - name: Build LipidSpace
      run: |
        qmake6 LipidSpace.pro 
        make clean 
        make release

    - name: Build LipidSpaceRest
      run: |
        qmake6 LipidSpaceRest.pro
        make clean 
        make release
  docker:
    name: Build and push LipidSpace Rest Docker image
    needs: build
    # build and push only for tags / releases
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: 'lifs/lipidspace'
      REGISTRY_NAME: 'docker.lifs-tools.org'
      BUILD_DATE: ${{ github.run_id }}.${{ github.run_attempt }}

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
        submodules: recursive          
    - name: Set Git user
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"

    - name: Login to LIFS Tools registry
      uses: docker/login-action@v1
      with:
        registry: docker.lifs-tools.org
        username: ${{ secrets.LIFS_TOOLS_DOCKER_REGISTRY_USER }}
        password: ${{ secrets.LIFS_TOOLS_DOCKER_REGISTRY_PW }}

    - name: Build the Docker image
      run: docker build . --file LipidSpaceRest.docker --tag ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}

    - name: Push Docker image
      run: docker push ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}
    
