name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: 'lifs/lipidspace'
      REGISTRY_NAME: 'docker.lifs-tools.org'
      BUILD_DATE: $(date +%s)
      
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
    - name: Set Git user
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"

    - name: Login to LIFS Tools registry
      uses: docker/login-action@v1
      with:
        registry: docker.lifs-tools.org
        username: ${{ secrets.LIFS_TOOLS_DOCKER_REGISTRY_USER }}
        password: ${{ secrets.LIFS_TOOLS_DOCKER_REGISTRY_PW }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ REGISTRY_NAME }}/${{ IMAGE_NAME }}:${{ BUILD_DATE }}
      
    - name: Push Docker image
      run: docker push ${{ REGISTRY_NAME }}/${{ IMAGE_NAME }}:${{ BUILD_DATE }}
